### ISSUE TITLE
Support Raspberry Pi RP-400

### ISSUE THREAD

**Issue by arky** [go-debos/debos-recipes#29]
It seems that the current RPI64 recipe doesn't boot in RP-400 with Debian Bookworm suite (the bulleye suite throws an error).  Has anyone figured out the correct kernel, bootloader and u-boot versions to support this device?

![ima_515a849](https://github.com/go-debos/debos-recipes/assets/808895/d681f985-babd-4608-8cb8-729bdfa8ee1d)

**Comment by arky** [comment]
@andhe Thanks for figuring the issue with RPI3Bplus. Wonder if you have any insights with this one? Thanks

**Comment by andhe** [comment]
I'm pretty sure the bookworm u-boot-rpi package does not have the patch required on newer rpi4 models (and possibly rpi400?) that modifies the devicetree at boot depending on what the bootloader says. (Apparently they made incompatible hardware changes without changing the model name.)

There was multiple attempts at sending patches upstream at the time, here's one of them:
https://lists.denx.de/pipermail/u-boot/2022-October/498498.html
Not sure if anything eventually landed and is available in a newvwr version. Also not sure if the rpi400 has the same problem.

**Comment by arky** [comment]
Thank you @andhe Rebuilding again Debian Sid/Unstable helped boot the OS.
