### ISSUE TITLE
HDMI not working when starting kernel

### ISSUE THREAD

**Issue by p3likan0** [go-debos/debos-recipes#5]
After message `starting kernel` from uboot, hdmi is not working.
Ideas?

**Comment by andhe** [comment]
I don't think this is a debos bug.

You also need to provide more info on which hardware and software you're using for anyone to have a chance to help you. A blind guess is that you might be using the rpi reference recipe and are affected by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/arm/boot/dts?id=544e784188f1dd7c797c70b213385e67d92005b6 ???

**Comment by stappersg** [comment]
There are two kind of people who can close this issue.
* The original reporter of this issue
* The owners of this github repository

Time will tell who did close this _I can't be bothered anymore by this issue_.
